services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Tstemplate\:
    resource: '../Classes/*'

  TYPO3\CMS\Tstemplate\Controller\TypoScriptTemplateInformationModuleFunctionController:
    public: true

  TYPO3\CMS\Tstemplate\Hooks\DataHandlerClearCachePostProcHook:
    public: true

  TYPO3\CMS\Tstemplate\Controller\TypoScriptTemplateModuleController:
    tags: [ 'backend.controller' ]

  TYPO3\CMS\Tstemplate\Controller\TyposcriptConstantEditorController:
    tags: [ 'backend.controller' ]

  TYPO3\CMS\Tstemplate\Controller\TypoScriptTemplateInformationController:
    tags: [ 'backend.controller' ]

  TYPO3\CMS\Tstemplate\Controller\TypoScriptObjectBrowserController:
    tags: [ 'backend.controller' ]

  TYPO3\CMS\Tstemplate\Controller\TemplateAnalyzerController:
    tags: [ 'backend.controller' ]
