services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Tstemplate\:
    resource: '../Classes/*'

  TYPO3\CMS\Tstemplate\Hooks\DataHandlerClearCachePostProcHook:
    public: true

  TYPO3\CMS\Tstemplate\TypoScript\IncludeTree\Visitor\IncludeTreeSourceAggregatorVisitor:
    public: true

  TYPO3\CMS\Tstemplate\TypoScript\IncludeTree\Visitor\IncludeTreeCommentAwareAstBuilderVisitor:
    public: true
    # This Ast builder visitor creates state and should not be re-used
    shared: false

